name: Build
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker build
      run: docker build "$GITHUB_WORKSPACE/" --file "Docker/build.dockerfile"