name: Build pull request
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - name: NPM install
      run: npm install
    - name: NPM build development
      run: npm run build
    - name: NPM build production
      run: npm run build:production